### ISSUE TITLE
Not convertible to IOHIDReportCallback

### ISSUE THREAD

**Issue by piratezstick** [bettse/KuandoSwift#2]
Hi,

I tried using your code but get the following error here:

`let inputCallback : IOHIDReportCallback = { inContext, inResult, inSender, type, reportId, report, reportLength in
            let this : BusyLight = unsafeBitCast(inContext, BusyLight.self)
            this.input(inResult, inSender: inSender, type: type, reportId: reportId, report: report, reportLength: reportLength)
        }`

> is not convertible to IOHIDReportCallback

Also at the 2 occurrences of IOHIDDeviceCallback.

**Comment by bettse** [comment]
I pulled down the latest code and it built successfully, although it gave me a warning about the selector syntax I was using (which I just pushed the change for). This is with Xcode 7.3.1 on OS X 10.11.5; What version are you using?

**Comment by piratezstick** [comment]
I am still on OS X 10.10 so I probably have to update this. Sorry for the inconvenience.

**Comment by bettse** [comment]
Not a problem.  When I first wrote it, I think I was on 10.10 or earlier, so maybe check the git log (if you comfortable with it) for earlier revisions.  I'm normally pretty good about calling out commits where I'm updating for a new OS or Xcode version.
