### ISSUE TITLE
Swift 3 - Callback issue

### ISSUE THREAD

**Issue by deeankmet** [bettse/KuandoSwift#4]
Hi,
After updating to Swift 3 (and fixing the obvious build errors) I'm having problems with the matchingCallback and removalCallback not being called.

My initUsb looks like this,
```
    func initUsb() {
        let deviceMatch = [kIOHIDProductIDKey: productId, kIOHIDVendorIDKey: vendorId ]
        let managerRef = IOHIDManagerCreate(kCFAllocatorDefault, IOOptionBits(kIOHIDOptionsTypeNone))
        
        IOHIDManagerSetDeviceMatching(managerRef, deviceMatch as CFDictionary?)
        IOHIDManagerScheduleWithRunLoop(managerRef, CFRunLoopGetCurrent(), CFRunLoopMode.defaultMode.rawValue);
        IOHIDManagerOpen(managerRef, 0);
        
        let matchingCallback : IOHIDDeviceCallback = { inContext, inResult, inSender, inIOHIDDeviceRef in
            let this : UsbHandler = unsafeBitCast(inContext, to: UsbHandler.self)
            this.connected(inResult, inSender: inSender!, inIOHIDDeviceRef: inIOHIDDeviceRef)
        }
        
        let removalCallback : IOHIDDeviceCallback = { inContext, inResult, inSender, inIOHIDDeviceRef in
            let this : UsbHandler = unsafeBitCast(inContext, to: UsbHandler.self)
            this.removed(inResult, inSender: inSender!, inIOHIDDeviceRef: inIOHIDDeviceRef)
        }
        
   
        
        IOHIDManagerRegisterDeviceMatchingCallback(managerRef, matchingCallback, unsafeBitCast(self, to: UnsafeMutableRawPointer.self))
        IOHIDManagerRegisterDeviceRemovalCallback(managerRef, removalCallback, unsafeBitCast(self, to: UnsafeMutableRawPointer.self))
    }
```

Any ideas or a swift 3 update coming? 
Really appreciate your work and thanks in advance

**Comment by bettse** [comment]
I hadn't really thought about this project, or how much Swift 3 would have an impact on this.  Glad to hear people are finding it useful.  I just pushed up a change that I hope fixes it (https://github.com/bettse/KuandoSwift/commit/cca3146deb95186a89842d49c52d03334f4edc99).  i had Xcode do a bunch of the update, and then made a few tweaks myself, one of which, using `rawValue` for `CFRunLoopMode.defaultMode`, I stole from your example; Thank you.

Using my Kuando as a test device, it seems to work, but please let me know if there are edge cases you run into while integrating it into your own use.

**Comment by deeankmet** [comment]
Thanks for the update, had some problems with threading and my application refused to update my UI. Putting all usb-handling in a separate background-thread solved it which makes sense. Strange thing is that the same thing worked in Swift 2.3. 

Anyways.. thanks again for the quick response.
