### ISSUE TITLE
no  IOHIDDeviceOpen() call?

### ISSUE THREAD

**Issue by jdouglas-nz** [bettse/KuandoSwift#5]
Heya, 

this isn't really an 'issue' per-se (well.. maybe?), but mainly am looking for some advice. 

First off, thank you for turning the horrible IOKit documentation into something practical. I think there is a potential for a small library in this sample, and I would be willing to help out with that if you were remotely interested.

I am writing an desktop app for both Windows and OS X, and I have the Windows app working using [this .NET HID library](https://github.com/mikeobrien/HidLibrary).

I send an array of bytes, and a light turns on (similar to what I imagine BusyLight.swift represents). 
However, using your code as a template, (and checking that the byte data is the same on both platforms), I am unable to get the light to turn on, as I am on the windows platform with the aforementioned library. 

I know the concepts are a little different across the platforms, but I don't see that the device itself is being opened [i.e. this](https://developer.apple.com/reference/iokit/iohiddevicedeviceinterface/open?language=objc#declarations).

Could this be why I cannot get the light to turn on?

Doing some debugging, I do get a device connected callback (after changing vendorID/productID of course), but nothing happens after I call `output(_:Data)`.

I know its pretty hard to help with such a small amount of info, but would you have any pointers or advice to help?

**Comment by bettse** [comment]
Do you prefix your data on Windows with a '0' as the report id?  I believe you won't need to do that on macOS.  Also, what function are you using on Windows; WriteFile, or HidD_SetOutputReport?

**Comment by jdouglas-nz** [comment]
Thanks for the speedy reply!


> Do you prefix your data on Windows with a '0' as the report id?

no, I do not do that on Windows. 

> I believe you won't need to do that on macOS

Ah. that could be part of it. Just remembering from BusyLight,  the call to `IOHIDDeviceSetReport` takes a reportID as a parameter. could this be related?

> Also, what function are you using on Windows; WriteFile, or HidD_SetOutputReport?

The library does a pretty good job of hiding that detail, but digging into source code, [I found this]( https://github.com/mikeobrien/HidLibrary/blob/master/src/HidLibrary/HidDevice.cs#L557) which shows it is a `WriteFile`, which also sounds like a difference to me compared to what BusyLight does?

**Comment by jdouglas-nz** [comment]
also related:
in BusyLight, you form a byte array like this:
```Swift
        //Turn on light to demonstrate sending a command
        let sound : UInt8 = 0
        let r : UInt8 = 0
        let g : UInt8 = 0xff
        let b : UInt8 = 0
        let bytes : [UInt8] = [0, 0, r, g, b, 0, 0, sound, 0, 0, 0, 0, 0, 0]
```
the initial two 0's.. is this device specific ? similarly with all the trailing 0's.

**Comment by bettse** [comment]
>which also sounds like a difference to me compared to what BusyLight does?

WriteFile on Windows is like IOHIDDeviceSetReport on macOS: it tries to write to an interrupt endpoint if it exists, and falls back to the control endpoint.  The naming conventions are not consistent between the platform, so don't read too much into it.

>. is this device specific ?

Yup, its the protocol for the Kuando/BusyLight

>this is also prefixed with reportID as discovered above in EDIT

On macOS, you wouldn't prefix it with the reportID.

Does your device respond in some way, so that you can validate the communication?

**Comment by jdouglas-nz** [comment]
> Does your device respond in some way, so that you can validate the communication?

Besides the initial `matchingCallback` firing and some startup lighting sequence on the device, I have not been able to verify whether something is actually being sent across. 

A lot of this is unfamiliar territory (as it probably appears), so how I would go about verifying that comms are happening is beyond my knowledge. 
If there was some sort of echo type capability, that would be awesome!.  I can get a reference/engineer's manual for the board, but a lot of it is similarly well beyond me.  

funny enough, when I use `IOHIDDeviceSetReportWithCallback`, my Mac crashes.. 

Feel free to close this issue if you'd like, you've been a huge help, and it is starting to venture out beyond the your example code.

**Comment by jdouglas-nz** [comment]
I found the solution!


Don't ask me why I did this, or better yet why this works... BUT.....

Changing `reportSize` to 64... it works! It seems 64 is a semi magic number.

[On this page](https://developer.apple.com/library/content/documentation/DeviceDrivers/Conceptual/HID/new_api_10_5/tn2187.html#//apple_ref/doc/uid/TP40000970-CH214-SW13), find "Listing 2-22  Registering a HID device input report callback routine", there is a block of code defining reportSize as 64. I was pretty desperate, so I tried it.. lol... go figure.

Again, thank you a lot for your time, You have been very helpful.

**Comment by bettse** [comment]
>Changing reportSize to 64... it works! It seems 64 is a semi magic number.

The report size is device specific (with 32 and 64 being common values).  

I'm glad this was helpful, although yours is not the target use case.  The intent is to demonstrate how to do HID in 'pure' Swift, for someone who is already familiar with HID and the requirements of their device.

**Comment by jdouglas-nz** [comment]
> The intent is to demonstrate how to do HID in 'pure' Swift, for someone who is already familiar with HID and the requirements of their device.

I understand, was my error in part, and hopefully not the case where the Windows C-level function isn't introducing side-effects (by not communicating intent) and padding out my 7 byte report to 32 || 64 bytes under the hood.

_(warning: my 2c ahead)._

However, consider developers in my shoes. There are hard deadlines as normal, and as much as we would love to dig into all the lower level detail of HID communication, this is left as a 'small task', and employers generally prefer that you do not reinvent the wheel so you can solve problems that do not have solutions already.

If you google "swift HID example", this repo comes up first. The inclusion of "swift" in the search is key here. When you look for Swift, you expect to find something that looks like Swift. Swift is moving away from the Objective-C / C ancestry in style, and is much more about a familiar, readable interface of a 'modern' language. Meaning that familiarity with the Objc/C conventions, and even Swift's subjectively ungraceful handling of pointers (by giving them a type) spells confusion all around.

Thats where some Swifty library to hide the low-level boilerplate detail of all the setup needed to communicate with a HID could be a huge value-add to the community. 

I understand that is well beyond the scope of "demonstrat[ing] how to do HID in 'pure' Swift", but there is a gap in the community libraries, and your repo is the closest thing to it.
